import sys
import os
sys.path.append(os.getcwd())
from sqlalchemy.orm import Session
from note_writer_lab.db import engine
from note_writer_lab.models import GoldStandardCase, Base

def ingest_gold_standard():
    """
    Ingests 'Gold Standard' cases into the database.
    Since we don't have the actual TSV files, we will mock this data 
    with known examples of Helpful and Not Helpful notes.
    """
    print("Ingesting Gold Standard Data (Mocked)...")
    
    # Mock Data
    # 2 Helpful cases (High Consensus)
    # 2 Not Helpful cases (Polarized/Low Quality)
    mock_cases = [
        {
            "tweet_id": "1234567890",
            "tweet_text": "The moon is made of cheese.",
            "note_id": "note_h1",
            "text": "This tweet claims the moon is made of cheese. However, Apollo missions brought back rock samples proving it is made of silicate rock. Source: NASA [NASA Link]",
            "classification": "HELPFUL",
            "original_rating_status": "HELPFUL_INFORMED"
        },
        {
            "tweet_id": "0987654321",
            "tweet_text": "Look at this weird photo of a person with 6 fingers.",
            "note_id": "note_h2",
            "text": "The image is generated by AI. The hands show 6 fingers and the text is gibberish, which are common artifacts of current image generation models.",
            "classification": "HELPFUL",
            "original_rating_status": "HELPFUL_INFORMED"
        },
        {
            "tweet_id": "1122334455",
            "tweet_text": "The government is hiding the truth about everything.",
            "note_id": "note_nh1",
            "text": "This is just liberal propaganda. They always lie about this stuff.",
            "classification": "NOT_HELPFUL",
            "original_rating_status": "NOT_HELPFUL_ARGUMENT_QUALITY"
        },
        {
            "tweet_id": "5544332211",
            "tweet_text": "I love ice cream.",
            "note_id": "note_nh2",
            "text": "I agree with this tweet! It's so true!",
            "classification": "NOT_HELPFUL",
            "original_rating_status": "NOT_HELPFUL_OPINION_SPECULATION"
        }
    ]

    with Session(engine) as session:
        # Clear existing data to avoid duplicates during dev
        session.query(GoldStandardCase).delete()
        
        for case in mock_cases:
            gs_case = GoldStandardCase(
                tweet_id=case["tweet_id"],
                tweet_text=case["tweet_text"],
                note_id=case["note_id"],
                text=case["text"],
                classification=case["classification"],
                original_rating_status=case["original_rating_status"]
            )
            session.add(gs_case)
        
        session.commit()
        print(f"Successfully ingested {len(mock_cases)} Gold Standard cases.")

if __name__ == "__main__":
    # Drop table to ensure schema update (Dev only)
    GoldStandardCase.__table__.drop(engine, checkfirst=True)
    # Ensure tables exist
    Base.metadata.create_all(engine)
    ingest_gold_standard()
